sudo: required
language: python
services:
  - docker
branches:
  only:
  - master
notifications:
  email:
    on_failure: always
    recipients:
      - f339339@gmail.com
script:
  - echo ' ----------------- STEP 0) UNIT TEST  ----------------- '
  - pytest -v tests 
  - echo ' ----------------- STEP 1) INDEED SCRAPING ----------------- '
  - python cron_indeed_scrapping_test.py
  - ls output && ls logs  && cat logs/log.txt 
  #- docker build -t web_scraping_env . && docker run -it web_scraping_env /bin/bash -c "python cron_test.py && bash travis_push_github.sh"
after_success:
  - echo 'push scraped file to slack...' && current_date=$(date +'%Y-%m-%d') && for file_name in $(ls output/*.csv) ;  do  echo $file_name $slack_channel &&  bash slack_push.sh -f $file_name -c $slack_channel -s $slack_token  -n "TRAVIS SLACK PUSH" -x " >>>> INDEED SCRAPING REPORT  $file_name" ; done

# deploy:
#   provider: script
#   script: bash travis_push_github.sh
#   skip-cleanup: true
#   target-branch: master
#   github-token: $GH_TOKEN
#   keep-history: true
#   verbose: true
#   on:
#     branch: master
# env:
#   global:
#     secure: Yfr36/XdwtZyjUBJwYTboFAfH5qqSYRd7d1vx/vHO1fCP4XtQWqT1Lvo5pfbHXghOjiJZZcfhO72inUKJ7er9QXznsGufj6nnQUJs/dOoBbfGnLSdvSYT6lpXTe7GYMbOgUsmYtjeD8S6pyL2L8xcX1fPZzsVD7v/edG9kZo1H9+fKCbVipBNf0IXO4DaE1H4vw77UVb6ysA3npxyIprM4jXUkZW3KFb7fA7/LENpS1NPniQxYe1LuUjzOpdJAG28WIeQnC/Cb+jz16cRtIV7HgukG0WnpHdszI+Xj4Kx+46URZnXW95cpZ2cq4Oywx98XZbC5uEXn3GeB/9JgvnuNsfsYOzhdCg29Ca/JGiUyri7F/x3mFxMfl2OoJeO50R4JTnwPrAHot8m914rP/VXtGZFPJQfXjoyKQJPnHFO0Yt+IJ9ziK3r3tLcdrbYngPuoBHFEYr4f87jOjdiyn/+1x9liLYh+Z0/6UdbQJRQnsAh+ghSvs1M7FIKY4eMHPW9qKPUbfsQIRckTzC6U7lX16eiPQk+wehJ7o//FB6MFOEvbownBcDUooITJXgC0Cvtpd831ktlkxPqyJh13X9URbEyD25zG58zI9Bq7RfeCjWN8LZaa7bLyjhDR2KzAvWDfKowbUShpznlSSSo2czn81kT1GXaAa4Iz215kNCDfs=