version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
           - docker-elk
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
           - docker-elk
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200"
    networks:
          - docker-elk
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
networks:
  docker-elk:
    driver: bridge