version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
           docker-network
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
           docker-network
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    environment:
          - "ELASTICSEARCH_URL=http://127.0.0.1:9200"
    networks:
           docker-network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
networks:
  docker-network:
    driver: bridge
